version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  app:
    image: rust-api:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
